### ISSUE TITLE
GlideX

### ISSUE THREAD

**Issue by TheLajuj** [jonathanpeppers/glidex#102]

**Comment by jonathanpeppers** [comment]
Do you need help with something?

**Comment by TheLajuj** [comment]
kinda im on IOS and maybe it’s my computer but i have a pretty good one and
i can’t seem to get it to run at 60 frames

**Comment by jonathanpeppers** [comment]
glidex is a Xamarin wrapper around the Android Glide library. I'm not sure anything can help you here for iOS.

**Comment by TheLajuj** [comment]
oh okay thank you
