### ISSUE TITLE
Image not Displaying.

### ISSUE THREAD

**Issue by AmjadSaab** [jonathanpeppers/glidex#104]
If I don't set HeightRequest and WidthRequest on the Image, it doesn't adjust automatically and thus the image is not visible. I need to image height and width to be dynamic. Please i need  a solution of this issue urgently.

**Comment by jonathanpeppers** [comment]
This is the same issue mentioned here: https://github.com/jonathanpeppers/glidex/issues/10#issuecomment-433109852

They somehow solved this problem in .NET MAUI, but I don't know the details. Glide is used by default in MAUI now.

If you know how to fix it, let me know! I would help with any pull requests you submit.
