### ISSUE TITLE
Future for MAUI

### ISSUE THREAD

**Issue by ziomek64** [jonathanpeppers/glidex#105]
Is this project  gonna be continued and moved to MAUI?

Kind regards

**Comment by jonathanpeppers** [comment]
dotnet/maui already uses Xamarin.Android.Glide for loading images on Android.

**Comment by yassinessadi** [comment]
I think 🤔 Xamarin.Android.Glide not working with me because I feel like the app start crashing when I scroll down
Project :
https://github.com/yassinessadi/NextLevel/tree/master/NextLevel

**Comment by jonathanpeppers** [comment]
Can you file a new issue, and share the stack trace of the crash? [`adb logcat`](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log) output would show it.

**Comment by yassinessadi** [comment]
[New Text Document.txt](https://github.com/jonathanpeppers/glidex/files/11579566/New.Text.Document.txt)

**Comment by yassinessadi** [comment]
[logs.txt](https://github.com/jonathanpeppers/glidex/files/11579608/logs.txt)

**Comment by jonathanpeppers** [comment]
This doesn't actually seem to have a useful error message inside? Can you do this:

```
# enable even more logging (optional)
adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
# clear the log
adb logcat -c
# Launch your app, let it crash, etc.
# save the log
adb logcat -d > log.txt
```
