### ISSUE TITLE
How to change Cache Directory?

### ISSUE THREAD

**Issue by PATRICKdallat** [jonathanpeppers/glidex#108]
Am I able to change the cache directory?
I want to be able to persist for certain scenarios.

**Comment by jonathanpeppers** [comment]
I think this question is similar to: https://github.com/jonathanpeppers/glidex/issues/83#issuecomment-716546790

If they let you configure it with Glide: https://bumptech.github.io/glide/

You should be able to set it in an `IGlideHandler`.

**Comment by PATRICKdallat** [comment]
Sorry I have been unable to find where to do so, could you point me closer to the area to set the cache directory? please

**Comment by PATRICKdallat** [comment]
I have figured out a jumping off point.

`var internalCacheDiskCacheFactory = new InternalCacheDiskCacheFactory(ApplicationContext, "example", IMAGE_DISK_CACHE_SIZE);
var glideBuilder = new GlideBuilder().SetDiskCache(internalCacheDiskCacheFactory);
Glide.Init(ApplicationContext, glideBuilder);`

Thanks for the speed response.
