### ISSUE TITLE
[Question] Probably my foult but it maybe help someone else (not compatiple with NetStandart2.0)

### ISSUE THREAD

**Issue by meliksahk** [jonathanpeppers/glidex#15]
When I want to install package glidex.forms from nuget I get this error set:
![image](https://user-images.githubusercontent.com/6935693/48557480-f2085a80-e8f7-11e8-8db7-9ab80b763854.png)

how can I fix this ?

**Comment by jonathanpeppers** [comment]
@meliksahk you should only be installing it in the Xamarin.Android application project. Your net standard project doesn’t need it.

**Comment by meliksahk** [comment]
@jonathanpeppers But what is the different with glidex and glidex.forms. I want to use glidex in xamarin forms so which one I have to install ?

**Comment by jonathanpeppers** [comment]
`glidex` is just the binding for the Glide Java library. `glidex.forms` is the "glue" that makes it work inside Xamarin.Forms.

Install `glidex.forms` in your Xamarin.Android app project, and follow the example in the readme: https://github.com/jonathanpeppers/glidex/blob/master/README.md#glidexforms-for-xamarinforms-on-android

Closing for now, but feel free to let me know if you run into something else!
