### ISSUE TITLE
ImageButton: You must not call setTag() on a view Glide is targeting

### ISSUE THREAD

**Issue by toomasz** [jonathanpeppers/glidex#16]
I noticed some images are not loaded when im using gliex.forms with my forms project. After enabling debug log following exception is there:

 Unexpected exception in glidex: Java.Lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting
11-25 18:35:38.650 W/glidex  (13060):   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <0ad2222fd7074badb5de547b1521aab0>:0 
11-25 18:35:38.650 W/glidex  (13060):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <0ad2222fd7074badb5de547b1521aab0>:0 
11-25 18:35:38.650 W/glidex  (13060):   at Android.Glide.RequestBuilder.Into (Android.Widget.ImageView view) [0x00031] in <11ae0431714345688234bc37c9dafe24>:0 
11-25 18:35:38.650 W/glidex  (13060):   at Android.Glide.GlideExtensions+<LoadViaGlide>d__0.MoveNext () [0x00303] in <427dfe7fb53c4ee294c990744f70970c>:0 
11-25 18:35:38.650 W/glidex  (13060):   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
11-25 18:35:38.650 W/glidex  (13060): java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting
11-25 18:35:38.650 W/glidex  (13060): 	at com.bumptech.glide.request.target.ViewTarget.getRequest(ViewTarget.java:265)
11-25 18:35:38.650 W/glidex  (13060): 	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:603)
11-25 18:35:38.650 W/glidex  (13060): 	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:682)
11-25 18:35:38.650 W/glidex  (13060): 	at md51558244f76c53b6aeda52c8a337f2c37.ListViewAdapter.n_getView(Native Method)
11-25 18:35:38.650 W/glidex  (13060): 	at md51558244f76c53b6aeda52c8a337f2c37.ListViewAdapter.getView(ListViewAdapter.java:100)
11-25 18:35:38.650 W/glidex  (13060): 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
11-25 18:35:38.650 W/glidex  (13060): 	at android.widget.AbsListView.obtainView(AbsListView.java:3189)
11-25 18:35:38.650 W/glidex  (13060): 	at android.widget.ListView.makeAndAddView(ListView.java:2197)
11-25 18:35:38.650 W/glidex  (13060): 	at android.widget.ListView.fillDown(ListView.java:824)
11-25 18:35:38.650 W/glidex  (13060): 	at android.widget.ListView.fillFromTop(ListView.java:885)
11-25 18:35:38.650 W/glidex  (13060): 	at android.widget.ListView.layoutChildren(ListView.java:1952)
11-25 18:35:38.650 W/glidex  (13060): 	at android.widget.AbsListView.onLayout(AbsListView.java:2961)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.View.layout(View.java:20836)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
11-25 18:35:38.650 W/glidex  (13060): 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.View.layout(View.java:20836)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
11-25 18:35:38.650 W/glidex  (13060): 	at md51558244f76c53b6aeda52c8a337f2c37.ListViewRenderer.n_onLayout(Native Method)
11-25 18:35:38.650 W/glidex  (13060): 	at md51558244f76c53b6aeda52c8a337f2c37.ListViewRenderer.onLayout(ListViewRenderer.java:65)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.View.layout(View.java:20836)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
11-25 18:35:38.650 W/glidex  (13060): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
11-25 18:35:38.650 W/glidex  (13060): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
11-25 18:35:38.650 W/glidex  (13060): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.View.layout(View.java:20836)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
11-25 18:35:38.650 W/glidex  (13060): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
11-25 18:35:38.650 W/glidex  (13060): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
11-25 18:35:38.650 W/glidex  (13060): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.View.layout(View.java:20836)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
11-25 18:35:38.650 W/glidex  (13060): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
11-25 18:35:38.650 W/glidex  (13060): 	at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.n_onLayout(Native Method)
11-25 18:35:38.650 W/glidex  (13060): 	at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.onLayout(NavigationPageRenderer.java:65)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.View.layout(View.java:20836)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
11-25 18:35:38.650 W/glidex  (13060): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
11-25 18:35:38.650 W/glidex  (13060): 	at md58432a647068b097f9637064b8985a5e0.MasterDetailContainer.n_onLayout(Native Method)
11-25 18:35:38.650 W/glidex  (13060): 	at md58432a647068b097f9637064b8985a5e0.MasterDetailContainer.onLayout(MasterDetailContainer.java:53)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.View.layout(View.java:20836)
11-25 18:35:38.650 W/glidex  (13060): 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
11-25 18:35:38.650 W/glidex  (13060): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
```

**Comment by toomasz** [comment]
One of the images started loading when I added WidthRequest and HeightRequest

Also ImageButton images doesn't seem to load, WidthRequest and HeightRequest doesn't help here.

**Comment by jonathanpeppers** [comment]
@PureWeen ugh, seems like Glide uses `Tag` on the `ImageView` internally...

Is it possible to remove usage of `Tag` in `ImageButton`?

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/4542

**Comment by jonathanpeppers** [comment]
Ok, so as a workaround until a new Xamarin.Forms release, I could:
1. Make an `ImageButtonRenderer` in glidex.forms that subclasses the built-in Xamarin.Forms one
2. Set `Tag` to `null` in the constructor, the renderer would otherwise not do anything

This could plausibly solve the problem in the interim.

**Comment by toomasz** [comment]
Removed problem with Image not visible without WidthRequest and HeightRequest, this is other issue , not related to this one as im not getting **You must not call setTag() on a view Glide is targeting** exception there

**Comment by jonathanpeppers** [comment]
Yeah @toomasz see #10 about WidthRequest or HeightRequest.

I am unsure what to do on that one yet.

**Comment by toomasz** [comment]
Yeah maybe it's the same issue but my image is in Grid and seems to not be shown with any Horizontal/Vertical options. I will create repro when I'm free.

**Comment by toomasz** [comment]
@jonathanpeppers Not sure if this is related but i got this exception when i tried last Glidex and Glidex.Forms compiled from latest commit:
```
12-16 02:11:01.976 I/MonoDroid(17440): System.NullReferenceException: Object reference not set to an instance of an object.
12-16 02:11:01.976 I/MonoDroid(17440):   at Xamarin.Forms.Platform.Android.ImageButtonRenderer.Draw (Android.Graphics.Canvas canvas) [0x000a5] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\ImageButtonRenderer.cs:206 
12-16 02:11:01.977 I/MonoDroid(17440):   at Android.Views.View.n_Draw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) [0x00011] in <1219ce5aae934ab095dc0e05b2110050>:0 
12-16 02:11:01.977 I/MonoDroid(17440):   at (wrapper dynamic-method) System.Object.106(intptr,intptr,intptr)
12-16 02:11:01.991 E/AppCenterCrashes(17440): Unhandled Exception from source=AndroidEnvironment
12-16 02:11:01.991 E/AppCenterCrashes(17440): System.NullReferenceException: Object reference not set to an instance of an object.
12-16 02:11:01.991 E/AppCenterCrashes(17440):   at Xamarin.Forms.Platform.Android.ImageButtonRenderer.Draw (Android.Graphics.Canvas canvas) [0x000a5] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\ImageButtonRenderer.cs:206 
12-16 02:11:01.991 E/AppCenterCrashes(17440):   at Android.Views.View.n_Draw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) [0x00011] in <1219ce5aae934ab095dc0e05b2110050>:0 
12-16 02:11:01.991 E/AppCenterCrashes(17440):   at (wrapper dynamic-method) System.Object.106(intptr,intptr,intptr)
12-16 02:11:02.215 W/zygote64(17440): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
```

**Comment by PureWeen** [comment]
@toomasz  a fix for that will be available in the 3.5 release of Forms

**Comment by jonathanpeppers** [comment]
It looks like a lot could be null inside `ImageButtonRenderer.Draw`, so not sure what is happening?

I don't see a commit that fixes something like this? https://github.com/xamarin/Xamarin.Forms/commits/master/Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs

@PureWeen do you know which PR it is? I might be able to add _another_ workaround to override `Draw` and either return out or `catch (NullReferenceException)`. ew.

**Comment by PureWeen** [comment]
Oops :-/ Apologies on that one.. I didn't look at the stacktrace close enough

I'll poke it and figure out where the NRE is coming from. Nothing is jumping out at me right away but should be easy enough to reproduce and fix quickly with 3.5

**Comment by PureWeen** [comment]
Yea it looks like when using GlideX there's a draw pass where the drawable hasn't been set yet so there's a null exception on the line where it's setting the bounds of the Drawable

I'll get a PR in for 3.5 that checks for null.

In the meantime :-/ a renderer like this does fix the issue

```C#
public class ImageButtonRenderer : Xamarin.Forms.Platform.Android.ImageButtonRenderer
    {
        public ImageButtonRenderer(Context context) : base(context)
        {
            //HACK: workaround until https://github.com/xamarin/Xamarin.Forms/pull/4542 is released
            // See https://github.com/jonathanpeppers/glidex/issues/16
            Tag = null;
        }

        public override void Draw(Canvas canvas)
        {
            try
            {
                base.Draw(canvas);
            }
            catch(System.NullReferenceException)
            {

            }
        }
    }
```

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/4783

**Comment by jonathanpeppers** [comment]
@toomasz can you try this `*.nupkg` and see if it works for you? https://ci.appveyor.com/project/jonathanpeppers/glidex/builds/21079587/artifacts

I tried to reproduce the bug myself, but it wasn't happening...

**Comment by PureWeen** [comment]
@jonathanpeppers The NRE exception in Draw?
You have to set the BackgroundColor of the ImageButton in order for the NRE exception to happen

**Comment by toomasz** [comment]
@jonathanpeppers I tried your packages, app does not crash with NullRefException but ImageButton doesnt display image and I saw  `Java.Lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting` in logcat. Maybe you want access to my repo? Seems my app is good for reproducing bugs. Im hosting on bitbucket so just give me your username.

**Comment by jonathanpeppers** [comment]
Ok, yeah I can repro with the `BackgroundColor`. I will merge #24 when it's green.

@toomasz would it be possible for you to contribute some layouts in the `glidex.forms.samples` project? You can makeup whatever you like. I generally go through all of those before I submit an update to NuGet.
