### ISSUE TITLE
Images don't load in Xamarin.Forms 4 when using Visual=Material

### ISSUE THREAD

**Issue by mikescandy** [jonathanpeppers/glidex#19]
As described in https://github.com/xamarin/Xamarin.Forms/issues/4674, when using XF4 and setting the ContentPage Visual to Material, images don't load. 
The visual code uses ContextThemeWrapper to apply Material themes to controls, but in GlideExtensions.cs:
```csharp
 if (imageView.Context is Activity activity)
else
return;
```
Without the else images are loaded correctly.

**Comment by mikescandy** [comment]
I'm trying to produce a minimal case for this but I can't... (these bugs are killing me! 🤬🤬🤬) 
I'll keep on trying....

**Comment by mikescandy** [comment]
Got it! Please find a repro at https://github.com/mikescandy/glidex/tree/wrapbug . I forgot that to trigger the issue I had to:
- upgrade to XF4
- upgrade to Support Libraries v28.0.0-preview8
- target Android 9.0
BUT
not for the binding project. I think there's a different Xamarin android bug there
Anyway, this shows the issue (and it might be a good starting point if/when you plan to update to the latest libs)

**Comment by jonathanpeppers** [comment]
So I started a branch here to try all the new stuff: https://github.com/jonathanpeppers/glidex/compare/xf-4.0-pre

Main thing I saw was `ImageCell` broke the moment I upgraded to 4.x: #21 

I'll look at what might be happening when `glidex.csproj` has a `TargetFrameworkVersion=v8.1`.

**Comment by mikescandy** [comment]
I think I saw an issue on xamarin.android that could be related to the binding project not compilinig, I'll see if I can link it here.

**Comment by jonathanpeppers** [comment]
If the binding project had:
```xml
<PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0-preview9" />
```
Then you have to use `TargetFrameworkVersion=v9.0`, right?

**Comment by mikescandy** [comment]
no, I think support 28 can multitarget

**Comment by jonathanpeppers** [comment]
It is working for me, could it be that you have `-preview8` in your example, and I have `-preview9`?

The other thing is I'm using a master build of Xamarin.Android + VS 2019: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-builds-master/656/PublishUrls/

**Comment by mikescandy** [comment]
I think the issue is fixed in master. I'll see if I can try that tomorrow too.

**Comment by jonathanpeppers** [comment]
The only thing I remember is this: https://github.com/xamarin/xamarin-android/pull/2424

I think you would get a build error on incremental builds, though.

**Comment by jonathanpeppers** [comment]
Oh sorry @mikescandy I didn't read!

> I think I saw an issue on xamarin.android that could be related to the binding project not compilinig, > > I'll see if I can link it here.
> edit: xamarin/xamarin-android#2465 (hey, look who created the issue 😅 )

If that's the issue, yeah I fixed it in xamarin-android/master. Here is a workaround: https://github.com/jonathanpeppers/glidex/commit/861719f365eaed53c855f8bc5721a82729e9d51b

I think we can close this, unless you are seeing this in the Android device log: https://github.com/jonathanpeppers/glidex/blob/4c32d3ba7de6e6bcdfdf84ad7c61af0b94d3e6d3/glidex.forms/GlideExtensions.cs#L28-L30

**Comment by mikescandy** [comment]
I do see 
```` 
12-14 15:01:10.569 W/glidex  ( 3824): Context `android.view.ContextThemeWrapper@f0bca8f` is not an Android.App.Activity, aborting image load for `Uri: https://growtix-melupufoagt.stackpathdns.com/media/big//34/28/23/5a9f03c2-3734-4486-bd04-2d45ac1c102e.png`.
```

**Comment by jonathanpeppers** [comment]
Ok I searched XF for `ContextThemeWrapper`, and looks like this would happen with `<Image/>` inside a `<Frame/>`:
```xml
<Frame>
    <Image WidthRequest="80" HeightRequest="80" Source="trump.png" />
</Frame>
```
`MaterialFrameRenderer` has a `ContextThemeWrapper` as its `Context`, and it would "pass it on" to its children.

**Comment by mikescandy** [comment]
That's how I triggered it in  https://github.com/mikescandy/glidex/tree/wrapbug
