### ISSUE TITLE
Request Listener support for android.

### ISSUE THREAD

**Issue by ahmedshibly** [jonathanpeppers/glidex#28]
Is it possible to add bindings for request listener in android.?

**Comment by jonathanpeppers** [comment]
Hi @ahmedshibly can you link/post an example (in Java) of what you are trying to do?

I would want to add to our sample project if I added this.

**Comment by ahmedshibly** [comment]
Have a look at [](https://github.com/bumptech/glide/issues/527)
`Glide
    .with(context)
    .load(imageUrl)
    .thumbnail(Glide // this thumbnail request has to have the same RESULT cache key
            .with(context) // as the outer request, which usually simply means
            .load(oldImage) // same size/transformation(e.g. centerCrop)/format(e.g. asBitmap)
            .fitCenter() // have to be explicit here to match outer load exactly
    )
    .listener(new RequestListener<String, GlideDrawable>() {
        @Override public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
            if (isFirstResource) {
                return false; // thumbnail was not shown, do as usual
            }
            return new DrawableCrossFadeFactory<Drawable>(/* customize animation here */)
                    .build(false, false) // force crossFade() even if coming from memory cache
                    .animate(resource, (ViewAdapter)target);
        }
    })
    //.fitCenter() // this is implicitly added when .into() is called if there's no scaleType in xml or the value is fitCenter there
    .into(imageView)
;`

**Comment by ahmedshibly** [comment]
`Glide
    .with(context)
    .load(imageUrl)
    .thumbnail(Glide // this thumbnail request has to have the same RESULT cache key
            .with(context) // as the outer request, which usually simply means
            .load(oldImage) // same size/transformation(e.g. centerCrop)/format(e.g. asBitmap)
            .fitCenter() // have to be explicit here to match outer load exactly
    )
    .listener(new RequestListener<String, GlideDrawable>() {
        @Override public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
            if (isFirstResource) {
                return false; // thumbnail was not shown, do as usual
            }
            return new DrawableCrossFadeFactory<Drawable>(/* customize animation here */)
                    .build(false, false) // force crossFade() even if coming from memory cache
                    .animate(resource, (ViewAdapter)target);
        }
    })
    //.fitCenter() // this is implicitly added when .into() is called if there's no scaleType in xml or the value is fitCenter there
    .into(imageView)
;`

**Comment by ahmedshibly** [comment]
Have a look at this comment.
[https://github.com/bumptech/glide/issues/527#issuecomment-148840717](url)

**Comment by jonathanpeppers** [comment]
So this is going to be tricky because this is a generic type:
```
new RequestListener<String, GlideDrawable>()
```
@ahmedshibly have you tried this component? https://www.nuget.org/packages/Xamarin.Android.Glide/

Does it seem to have the full API for this?

I have been considering switching to it, and dropping the binding for glidex in this repo.

**Comment by ahmedshibly** [comment]
Currently I am using my own binding. 
One admin at  [https://xamarin.uservoice.com/forums/145075-xamarin-component-ideas/suggestions/12375513-glide](url) has suggested your binding so I tried to use glidex. 
You use my binding if you want.

**Comment by jonathanpeppers** [comment]
@ahmedshibly I don't know who that admin is, but there is an "official" Xamarin component for Glide now on [NuGet](https://www.nuget.org/packages/Xamarin.Android.Glide/).

It looks like they have the API you linked to: https://www.fuget.org/packages/Xamarin.Android.Glide/4.0.0/monoandroid70/lib/Xamarin.Android.Glide.dll/Bumptech.Glide.Request/IRequestListener#IRequestListener

**Comment by taublast** [comment]
As far as i understand "the official" one is not supporting forms.
Actually looking to get events when image is loaded and image failed to load from remote. Also wanted to get original remote image size as explained here http://github.com/bumptech/glide/issues/781#issuecomment-160953996 but need more bindings for this indeed.

**Comment by jonathanpeppers** [comment]
@taublast maybe what I'm missing here is:

> What do you actually need to do?

I think @ahmedshibly was using the Glide binding here directly (he can correct me if I'm wrong).

My first goal is:
* See if this repo can just use the official Xamarin binding for Glide. (I may have to send them a few fixes, and wait for another release, we'll see)
* Expose what you need to do in glidex.forms via some new API that doesn't exist yet. Unfortunately, I don't know what you're trying to do?

More detail would help? File a new issue if you think it makes sense, @taublast, thanks!

**Comment by taublast** [comment]
@jonathanpeppers If we get Listener we can:
1 respond to events when an image is loaded or failed to load. this is what we have with ffimageloading atm, managed to have it without plugins with a custom renderer on ios but not on android. If i switch from ffimageloading to glidex i would need to implement such events, can't do it without listener.
2 obtain the loaded original remote image size before it would be assigned to view.

**Comment by tipa** [comment]
I also would appreciate RequestListener support. This binding library supports it, but is "stuck" on Glide v4.1.1: https://github.com/beraybentesen/glide-xamarin-android

**Comment by jonathanpeppers** [comment]
Follow #35 for updates.

An update for [Xamarin.Android.Glide](https://www.nuget.org/packages/Xamarin.Android.Glide/) will be shipping soon, that is the official binding from [here](https://github.com/xamarin/XamarinComponents/tree/master/Android/Glide).

**Comment by ahmedshibly** [comment]
@tipa try this,  this is based on v4.7 and has request listener support : [https://github.com/ahmedshibly/Xam.Glide](url)

**Comment by jonathanpeppers** [comment]
They just shipped an official update with 4.9: https://www.nuget.org/packages/Xamarin.Android.Glide/4.9.0

If any of you guys have fixes to the binding, contribute them [here](https://github.com/xamarin/XamarinComponents/tree/master/Android/Glide).

Thanks! I'll be working on #35 when I have some free time (lol?).

**Comment by jonathanpeppers** [comment]
@taublast (or anybody, feel free!) does it seem like you can achieve what you need with the new `IGlideHandler` interface I'm working on here: https://github.com/jonathanpeppers/glidex/pull/41

Reviews welcome ☝️ 

It looks like `SimpleTarget` from `Xamarin.Android.Glide` gives all the callbacks needed.
