### ISSUE TITLE
Problem with glidex when i've updated the visual studio version

### ISSUE THREAD

**Issue by kelvice** [jonathanpeppers/glidex#3]
I've been using your Glidex library in my xamarin forms projectes without problems... But a colleague, updated to the last version of visual studio and the render of the controls is horrible... It has broken everything... What can i do? I have looked for information but i haven't found anything. I copy to you the image of the login before and after:

Thank you for your help.

Previous version:

![image](https://user-images.githubusercontent.com/13480845/42455722-515b45d0-8393-11e8-95e8-57b05de938e6.png)

Microsoft Visual Studio Community 2017 Version 15.4.5
Xamarin   4.7.10.38 (34c1b6c)
Xamarin.Android SDK   8.0.2.1 (HEAD/c2a33d8ea)
Xamarin.iOS and Xamarin.Mac SDK   11.3.0.47 (51128b8)

Last version:

![image](https://user-images.githubusercontent.com/13480845/42455602-03c136ea-8393-11e8-925e-11b02d83e4ce.png)

Microsoft Visual Studio Enterprise 2017 Versión 15.7.4
Xamarin   4.10.10.2 (35a01d8dc)
Xamarin Designer   4.12.1 (f3257e429)
Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)

**Comment by jonathanpeppers** [comment]
What version of Xamarin.Forms are you using?

This should be in your `packages.config` or a `<PackageReference />` in your `*.csproj`.

Also I would try this (just to verify):
- Does a `Rebuild` fix it?
- If you manually delete all `bin`/`obj` folders, restart Visual Studio, and try again does it fix it?

**Comment by kelvice** [comment]
The xamarin forms version is -->  id="Xamarin.Forms" version="2.3.4.270"

And i have tried everything, Rebuild, clean, delete manually bin/obj and reset, uninstall app..... But everything is the same, not fixed :-(

**Comment by jonathanpeppers** [comment]
Hmm, minimum version of Xamarin.Forms for glidex.forms is 2.4.0.280: https://www.nuget.org/packages/glidex.forms/1.0.0

If you are upgrading Xamarin.Forms, I would disable glidex temporarily and test the upgrade by itself:
```csharp
//Comment this line, and remove the glidex.forms NuGet
//Android.Glide.Forms.Init ();
```

Put it back after you verified the Xamarin.Forms upgrade is working fine.

**Comment by kelvice** [comment]
Hello again, I have updated xamarin and it works :-) 

But i have found another thing. Everything works fine, but if i have the app open and i close the app going back and it crashes. It throws an unhandled exception that is: 
"Unable to activate instance of type Android.Glide.ImageRenderer from native handle 0xbffbdcac (key_handle 0x80d5fbd)."

It doesn't affect to the app performance but it's not desirable... Have you seen that error anytime??
Thank you

**Comment by jonathanpeppers** [comment]
I have been working on a new release, and I think I saw this myself and fixed it: https://github.com/jonathanpeppers/glidex/commit/d28d13fe1d740a6d329effdbf816122a8e4eaebb

Maybe this is a good enough fix to to warrant an update. I also updating Glide itself.

**Comment by kelvice** [comment]
Ok thank you for the fast answer :-) And when will you upload the update? Only to know :-)

**Comment by jonathanpeppers** [comment]
I just pushed an update that should be available shortly: https://www.nuget.org/packages/glidex.forms/1.0.1

Test it out for me and let me know if something broke! I have no QA team, it's just me.

Closing this for now.
