### ISSUE TITLE
Question - GlideX with 3rd partly libs

### ISSUE THREAD

**Issue by Pinox** [jonathanpeppers/glidex#31]
Hi Guys,

I'm currently using FFimageloading for images on Android + iOS in XF. 
https://github.com/luberda-molinet/FFImageLoading

Does anyone know if glideX can be used with said library to improve performance on Android.

Also , is there functionality in GlideX where we can preload images in cache for later use on device and the ability the retry images loads.

Thanks in advance.

**Comment by jonathanpeppers** [comment]
It looks like FFImageLoading replaces any `IImageSourceHandler` or `IImageViewHandler` implementations with its own image loading: https://github.com/luberda-molinet/FFImageLoading/blob/0d2829e410a614d41445e8fc45a0635e4b21a768/source/FFImageLoading.Forms.Droid/CachedImageRenderer.cs#L281

I would not try to use glidex and FFImageLoading at the same time.

As for preloading, you would need to use the binding for Glide directly, here is an example of how they do it in Java:
* https://stackoverflow.com/questions/37964187/preload-multiple-images-with-glide

This _should_ work if you want to try to use the types the binding exposes in the [Android.Glide](https://www.fuget.org/packages/glidex/1.0.4/lib/monoandroid81/glidex.dll/Android.Glide) namespace, let me know if something is missing: we don't have an example of doing this.

**Comment by jonathanpeppers** [comment]
@Pinox if you are still wanting to do this, here is a blog post of someone that mixed `FFImageLoading` and `glidex`: https://www.sharpnado.com/ultimate-image-caching/

YMMV, but it works? I think that answers this question, let me know, thanks!

**Comment by Pinox** [comment]
thanks @jonathanpeppers .  Yes I saw that on the Xamarin blog.  I do understand from Ffimageloading authors that they are working on rewriting part of android code for more performant code and incorporating some of glidex features.
