### ISSUE TITLE
Load bitmap to draw on canvas

### ISSUE THREAD

**Issue by velocitysystems** [jonathanpeppers/glidex#37]
I would like to use _glidex_ to load a bitmap from a source and expose the object so I can draw it directly on a canvas, similar to the Java code below.

However, `SimpleTarget<T>` doesn't appear to be supported by _glidex_ yet? i.e.

```
Glide.with(yourApplicationContext))
    .load(youUrl)
    .asBitmap()
    .into(new SimpleTarget<Bitmap>(myWidth, myHeight) {
        @Override
        public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
            // Do something with bitmap here.
        }
    };
```

**Comment by jonathanpeppers** [comment]
The plan is to somehow expose APIs like this in glidex.forms.

I am waiting on an update to [Xamarin.Android.Glide](https://www.nuget.org/packages/Xamarin.Android.Glide/) before we can do that.

You can follow progress here: https://github.com/jonathanpeppers/glidex/pull/35

**Comment by jonathanpeppers** [comment]
If you want to try the prerelease: https://www.nuget.org/packages/glidex.forms/2.0.0-pre1

I have an example of using `SimpleTarget`: https://github.com/jonathanpeppers/glidex/blob/ebae223e57e17d21a33fc7a3e6adb45b85249206/glidex.forms.sample/RandomAlphaHandler.cs#L24

File an issue if you find any problems or missing APIs, thanks!
