### ISSUE TITLE
[Question] When the new Update based on XA.Glide will be available?

### ISSUE THREAD

**Issue by Sergiojoel9877** [jonathanpeppers/glidex#40]
When the new update based in Xamarin.Android.Glide could be available on Nuget?

**Comment by jonathanpeppers** [comment]
So far all I've done is switch over to it. I would like to actually expose some new APIs before I ship a release.

A `nupkg` is built on every commit, so you can try that now if you like: https://ci.appveyor.com/project/jonathanpeppers/glidex/builds/24375797/artifacts

**Comment by jonathanpeppers** [comment]
It should be live shortly: https://www.nuget.org/packages/glidex.forms/2.0.0-pre1

File a new issue if you find any problems, thanks!

**Comment by Sergiojoel9877** [comment]
Nice!
