### ISSUE TITLE
Can't use resource:// 

### ISSUE THREAD

**Issue by alexthekid07** [jonathanpeppers/glidex#42]
GlideX does not seem to like when you reference an embedded resource from a PCL with a URI like:
"resource://MyApp.embedded.defaultProfile.png"

It works fine with a standard Image and in FFImageLoading, so I was hoping it would work here but it barks about an invalid/missing content provider.

> 06-19 17:18:14.786 W/Glide   ( 5080): Load failed for resource://MyApp.embedded.loginlogo.png with size [1794x1794]
> 06-19 17:18:14.786 W/Glide   ( 5080): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
> 06-19 17:18:14.786 W/Glide   ( 5080): There was 1 cause:
> 06-19 17:18:14.786 W/Glide   ( 5080): java.io.FileNotFoundException(No content provider: resource://MyApp.embedded.loginlogo.png)
> 06-19 17:18:14.786 W/Glide   ( 5080):  call GlideException#logRootCauses(String) for more detail
> 06-19 17:18:14.786 W/Glide   ( 5080):   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
> 06-19 17:18:14.786 W/Glide   ( 5080): There was 1 cause:
> 06-19 17:18:14.786 W/Glide   ( 5080): java.io.FileNotFoundException(No content provider: resource://MyApp.embedded.loginlogo.png)
> 06-19 17:18:14.786 W/Glide   ( 5080):  call GlideException#logRootCauses(String) for more detail
> 06-19 17:18:14.786 W/Glide   ( 5080):     Cause (1 of 1): class java.io.FileNotFoundException: No content provider: resource://MyApp.embedded.loginlogo.png
> 06-19 17:18:14.786 I/Glide   ( 5080): Root cause (1 of 1)
> 06-19 17:18:14.786 I/Glide   ( 5080): java.io.FileNotFoundException: No content provider: resource://MyApp.embedded.loginlogo.png
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1444)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1295)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1218)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at java.lang.Thread.run(Thread.java:764)
> 06-19 17:18:14.786 I/Glide   ( 5080): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

**Comment by jonathanpeppers** [comment]
@alexthekid07 I don't think `resource://` works in stock Xamarin.Forms--I've actually never seen it before.

Is this a feature of FFImageLoading? https://github.com/luberda-molinet/FFImageLoading/wiki/Data-URL-&-Embedded-Resources-support-(including-base64)#embedded-resources-uri-support

**Comment by jonathanpeppers** [comment]
I looked at the Xamarin.Forms source, and I am pretty confident they don't support `resource://`. I don't think I want to implement non-standard URIs in glidex.forms.

I would also recommend _not_ using `EmbeddedResource` for your images anyway. They are the poorest for performance.

Closing for now, let me know if you see something different. Thanks!
