### ISSUE TITLE
Fast Renderers Access Issue

### ISSUE THREAD

**Issue by chrisfoulds** [jonathanpeppers/glidex#54]
I've just installed this with the hope of speeding up a production Xamarin forms app on 3.6.0
(Can't update to 4+ currently).

In 
public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity

I have

`Xamarin.Forms.Forms.SetFlags("FastRenderers_Experimental");
            global::Xamarin.Forms.Forms.Init(this, bundle);
            Android.Glide.Forms.Init(this);`

Below is some of my init code yet I am getting the following exception ....
Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer..ctor(Android.Content.Context)' is inaccessible from method `Android.Glide.ImageRenderer..ctor(Android.Content.Context)

**Comment by chrisfoulds** [comment]
Full stack
`10-10 20:27:00.811 E/AndroidRuntime(29023): md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper: (MethodAccessException) Method `Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer..ctor(Android.Content.Context)' is inaccessible from method `Android.Glide.ImageRenderer..ctor(Android.Content.Context)'
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at   at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_throw_method_access(intptr,intptr).(unknown.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Android.Glide.ImageRenderer..ctor(Android.Content.Context context)[0x00000](Android/Glide/ImageRenderer/0x00000.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at   at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&).(unknown.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at System.Reflection.MonoCMethod.InternalInvoke(System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions)[0x00013](System/Reflection/MonoCMethod0x00013.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at System.Reflection.MonoCMethod.DoInvoke(System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)[0x0007a](System/Reflection/MonoCMethod0x0007a.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at System.Reflection.MonoCMethod.Invoke(System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)[0x00000](System/Reflection/MonoCMethod0x00000.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark)[0x0022b](System/RuntimeType0x0022b.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at System.Activator.CreateInstance(System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes)[0x000a1](System/Activator0x000a1.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at System.Activator.CreateInstance(System.Type type, System.Object[] args)[0x00000](System/Activator0x00000.cs:1)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate(System.Type type, System.Object source, System.Type visualType, System.Object[] args)[0x000af](D:\a\1\s\Xamarin.Forms.Core\DependencyResolver.cs:58)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandler(System.Type type, System.Object source, Xamarin.Forms.IVisual visual, System.Object[] args)[0x00052](D:\a\1\s\Xamarin.Forms.Core\Registrar.cs:71)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandlerForObject[TOut](System.Object obj, System.Object[] args)[0x0002c](D:\a\1\s\Xamarin.Forms.Core\Registrar.cs:103)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(Xamarin.Forms.VisualElement element, Android.Content.Context context)[0x00000](D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:339)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)[0x000af](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)[0x00139](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.Load()[0x00000](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager(Xamarin.Forms.Platform.Android.VisualElementPackager packager)[0x00007](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:414)
10-10 20:27:00.811 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement(TElement element)[0x000e0](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement(Xamarin.Forms.VisualElement element)[0x00027](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(Xamarin.Forms.VisualElement element, Android.Content.Context context)[0x0001f](D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:341)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)[0x000af](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)[0x00139](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.Load()[0x00000](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager(Xamarin.Forms.Platform.Android.VisualElementPackager packager)[0x00007](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:414)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement(TElement element)[0x000e0](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement(Xamarin.Forms.VisualElement element)[0x00027](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(Xamarin.Forms.VisualElement element, Android.Content.Context context)[0x0001f](D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:341)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)[0x000af](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)[0x00139](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementPackager.Load()[0x00000](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager(Xamarin.Forms.Platform.Android.VisualElementPackager packager)[0x00007](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:414)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement(TElement element)[0x000e0](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement(Xamarin.Forms.VisualElement element)[0x00027](D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(Xamarin.Forms.VisualElement element, Android.Content.Context context)[0x0001f](D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:341)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.AppCompat.Platform.AddChild(Xamarin.Forms.Page page, System.Boolean layout)[0x0000d](D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:350)
10-10 20:27:00.815 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPageInternal(Xamarin.Forms.Page newRoot)[0x000ac](D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:320)
10-10 20:27:00.816 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPage(Xamarin.Forms.Page newRoot)[0x00087](D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:275)
10-10 20:27:00.816 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage(Xamarin.Forms.Page page)[0x00039](D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:330)
10-10 20:27:00.816 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage()[0x00000](D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:359)
10-10 20:27:00.816 E/AndroidRuntime(29023): 	at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication(Xamarin.Forms.Application application)[0x00282](D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:138)`

**Comment by chrisfoulds** [comment]
Is there a minimum version of Xamarin.Android my build needs ?

**Comment by chrisfoulds** [comment]
Everything is updated, latest VS , latest nugets for everything except xamarin forms which is 3.6
Total clean build etc.
Same crash
Do I need an older nuget for forms 3.6?

**Comment by jonathanpeppers** [comment]
@chrisfoulds OK, it looks like the fast renderer used to be `internal`: https://github.com/xamarin/Xamarin.Forms/blob/8317fcd9a46d83c613af3809883541b0449aba80/Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs#L14

In 4.0.0, it's not: https://github.com/xamarin/Xamarin.Forms/blob/4.0.0/Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs#L14

The fix will be to make glidex.forms require Xamarin.Forms 4.0.

What you could do:
* Use the latest 1.x version of glidex.forms
* Fork/copy the source of glidex.forms, and use the other `ImageRenderer` in your project

**Comment by chrisfoulds** [comment]
Thanks, glad I wasn't going crazy :-) , I will do a quick fork and put in in place.
