### ISSUE TITLE
GlideX doesn't show images at the beginning

### ISSUE THREAD

**Issue by SeRgI1982** [jonathanpeppers/glidex#56]
#  🐛 Bug Report

### Expected behavior

Image should be visible from the beginning

### Reproduction steps
Download [project](https://drive.google.com/open?id=1qUCXd2IXf6_T5jO85l4NbT34N2engqCw)

GlideXIssue.Android has installed GlideX.Forms

LoginPage or MainPage rotate device to Landscape mode - image appears
LoginPage focus Entry - image appears.

GlideXNoIssue.Android is a copy of GlideXIssue.Android without GlideX.Forms

Image appears from the beginning

### Configuration
Version GlideX.Forms: 2.0.0.336
Version Xamarin Forms: 4.2.0.848062

### Platform:

 🤖 Android
Device: Xiaomi Mi A2 Lite (API 28), Android emulator (API 28)

**Comment by jonathanpeppers** [comment]
Do you just need to set a `HeightRequest` or `WidthRequest` on the image?

There is a fundamental concept flaw between Forms & Glide: https://github.com/jonathanpeppers/glidex/issues/10#issuecomment-433109852

Basically Glide wants to know the size of the image to load a scaled down image, so it uses the size of the `ImageView`. Forms wants to know the size of the _actual_ image to impact your layout.

You end up with Glide thinking the image is 0x0...

**Comment by SeRgI1982** [comment]
Thanks @jonathanpeppers.
Fundamental concept between Forms & Glide surprised me.
