### ISSUE TITLE
crash after XF 4.4 release.

### ISSUE THREAD

**Issue by heebaek** [jonathanpeppers/glidex#57]
When back to launcher from top page with image,

No constructor found for Android.Glide.ImageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

if i add a fake ctor, exception is not throwing.
public ImageRenderer(System.IntPtr intPtr, Android.Runtime.JniHandleOwnership jniHandleOwnership) { }

you can test this easily with default sample project(Shell Forms app template), please try  back button from about tab(they use Xamarin logo image).

**Comment by jonathanpeppers** [comment]
@heebaek you made a new project that reproduces this? Can you upload it here? Thanks!

**Comment by heebaek** [comment]
ok. this is default empty template project and i added one image. (but image not visible...this is bug too.)

there are no tabs, so you just need to click back button after launch.

[glidex.zip](https://github.com/jonathanpeppers/glidex/files/3958634/glidex.zip)

**Comment by jonathanpeppers** [comment]
Thanks, yeah this is jacked up!

**Comment by jonathanpeppers** [comment]
@heebaek try out the latest update for me, and let me know, thanks!

https://www.nuget.org/packages/glidex.forms/2.0.1.394

**Comment by heebaek** [comment]
crash bug has been fixed.
but the image still doesn't display correctly sometimes.

**Comment by jonathanpeppers** [comment]
glide has a behavior difference, you will need to supply WidthRequest or HeightRequest as mentioned here: https://github.com/jonathanpeppers/glidex/issues/10#issuecomment-434838704

I have not figured out a way to get around this issue yet.
