### ISSUE TITLE
Can't use with Android 10 / AndroidX

### ISSUE THREAD

**Issue by velocitysystems** [jonathanpeppers/glidex#62]
Since `glidex.forms` takes a dependency on `Xamarin.Android.Glide` this in turn takes a dependency on` Xamarin.Android.Support.v4 (>= 28.0.0.1)`.

We are targeting Android 10 with AndroidX libraries and cannot install the NuGet package.
Is there any workaround or can we expect an updated version to be released?

**Comment by jonathanpeppers** [comment]
It looks like Glide 4.10.0 migrated to AndroidX:

https://github.com/bumptech/glide/releases

But I think we need a new Xamarin.Android.Glide that is based on AndroidX first?

https://github.com/xamarin/XamarinComponents/blob/ea469ecfc61ab0f7820e10031f85ceb33ad3f697/Android/Glide/build.cake#L6

Can you file an issue here? https://github.com/xamarin/XamarinComponents/issues

I'll leave this open, but basically I will publish a new version of glidex.forms once there is a new Xamarin.Android.Glide.

**Comment by velocitysystems** [comment]
Hi @jonathanpeppers. I have raised an issue with the Xamarin components team but am still awaiting a response.
Just wondering if you may possibly be able to gain some traction on this internally?

**Comment by jonathanpeppers** [comment]
This should be live shortly: https://www.nuget.org/packages/glidex.forms/2.1.0.470

I didn't test the NuGet package itself, let me know if you have an issue, thanks!

**Comment by velocitysystems** [comment]
Thanks Jonathan, look forward to testing tomorrow.

Great work!

**Comment by velocitysystems** [comment]
@jonathanpeppers Tested this morning and works well. I did find a disposing-related issue, but I don't believe it is related to the update and will bug accordingly. Thanks!

**Comment by Paul-DotNET** [comment]
Hi @jonathanpeppers ! Thanks for this amazing & useful plugin.
#95 - some images from drawable folder seems not loading.
