### ISSUE TITLE
Update to Xamarin.Android.Glide 4.11.0

### ISSUE THREAD

**Issue by podgorodetskiy** [jonathanpeppers/glidex#64]
Please update to new version of Xamarin.Android.Glide
https://www.nuget.org/packages/Xamarin.Android.Glide/4.11.0

**Comment by jonathanpeppers** [comment]
This should be live shortly: https://www.nuget.org/packages/glidex.forms/2.1.0.470

I didn't test the NuGet package itself, let me know if you have an issue, thanks!
