### ISSUE TITLE
Cannot install nuget package in Xamarin.Forms

### ISSUE THREAD

**Issue by sriganesh040194** [jonathanpeppers/glidex#66]
I have a Xamarin.Forms(4.7.0.1080) application with Xamarin.Android.
I tried to install Glidex.Forms from Nuget(2.1.0.470 latest stable), but it fails every time with compatibility issues.

I tried with both .netStandard v2.0 and v2.1. I get the same error except for the version info down below.

```Getting restore information for project /Users/SriGanesh/Projects/GroChop/GroChop/GroChop.csproj
Getting restore information for project /Users/SriGanesh/Projects/GroChop/GroChop.UITests/GroChop.UITests.csproj
Getting restore information for project /Users/SriGanesh/Projects/GroChop/GroChop.Web/GroChop.Web.csproj
Running non-parallel restore.
Reading project file /Users/SriGanesh/Projects/GroChop/GroChop/GroChop.csproj.
Restoring packages for /Users/SriGanesh/Projects/GroChop/GroChop/GroChop.csproj...
Restoring packages for .NETStandard,Version=v2.1...
Resolving conflicts for .NETStandard,Version=v2.1...
Checking compatibility of packages on .NETStandard,Version=v2.1.
Checking compatibility for GroChop 1.0.0 with .NETStandard,Version=v2.1.
Checking compatibility for Newtonsoft.Json 12.0.3 with .NETStandard,Version=v2.1.
Checking compatibility for Xamarin.Essentials 1.5.3.2 with .NETStandard,Version=v2.1.
Checking compatibility for Xamarin.FFImageLoading 2.4.11.982 with .NETStandard,Version=v2.1.
Checking compatibility for Xamarin.FFImageLoading.Forms 2.4.11.982 with .NETStandard,Version=v2.1.
Checking compatibility for Xamarin.FFImageLoading.Transformations 2.4.11.982 with .NETStandard,Version=v2.1.
Checking compatibility for Xamarin.Forms 4.7.0.1080 with .NETStandard,Version=v2.1.
Checking compatibility for Xamarin.Forms.PancakeView 1.4.2 with .NETStandard,Version=v2.1.
Checking compatibility for glidex.forms 2.0.1.394 with .NETStandard,Version=v2.1.
Package glidex.forms 2.0.1.394 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package glidex.forms 2.0.1.394 supports: monoandroid81 (MonoAndroid,Version=v8.1)
Checking compatibility for System.Numerics.Vectors 4.5.0 with .NETStandard,Version=v2.1.
Checking compatibility for System.ComponentModel 4.3.0 with .NETStandard,Version=v2.1.
Checking compatibility for Xamarin.Android.Glide 4.9.0 with .NETStandard,Version=v2.1.
Package Xamarin.Android.Glide 4.9.0 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Xamarin.Android.Glide 4.9.0 supports: monoandroid81 (MonoAndroid,Version=v8.1)
Checking compatibility for System.Runtime 4.3.0 with .NETStandard,Version=v2.1.
Checking compatibility for Microsoft.NETCore.Platforms 1.1.0 with .NETStandard,Version=v2.1.
Checking compatibility for Microsoft.NETCore.Targets 1.1.0 with .NETStandard,Version=v2.1.
Incompatible packages: 2
Package restore failed. Rolling back package changes for 'GroChop'. 
```

Can you please help?

**Comment by jonathanpeppers** [comment]
@sriganesh040194 it looks like you are trying to install `glidex.forms` in a `netstandard2.0` project.

You should only need this package in the head Xamarin.Android app project. Is that the issue?

**Comment by sriganesh040194** [comment]
@jonathanpeppers  Thanks for your response. No, it is not an issue. I can install ```glidex.forms``` in Xamarin.Android. 

But I get this error which says, I need ```glidex``` as well.

```/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error XA2002: Can not resolve reference: `Xamarin.Android.Glide`, referenced by `glidex.forms`. Please add a NuGet package or assembly reference for `Xamarin.Android.Glide`, or remove the reference to `glidex.forms`. (XA2002)```


Now, I added ```glidex``` from Nuget along with ```glidex.forms```, but still the same error.

**Comment by jonathanpeppers** [comment]
Let me unlist `glidex`, as this is from the past. It was a Java binding for Glide, but I started using `Xamarin.Android.Glide` instead when we got an official Xamarin binding for it.

Add `Xamarin.Android.Glide`, then `glidex.forms`.

I'm also guessing you are using `packages.config`? I think you would have an easier time using `PackageReference`.

**Comment by sriganesh040194** [comment]
That is great. Thank you very much for your help. 

I think I am using PackageReference, I am new to Xamarin and I used the default Shell Template and built on top of that. I couldn't find ```package.config`` in my project.

I added ```Xamarin.Android.Glide``` and ```glidex.forms``` Now it seems to work fine.

However, there were some hiccups. It might help someone in the future.

- ```Xamarin.Android.Glide``` targets mono android v10.0, I upgraded my Android project's target framework to Android 10 (API 29) and installed the Android 10 (API 29) SDK tools for the project to deploy in my emulator.
- If you are using PancakeView, then you need to add ```Xamarin.Android.Support.Compact```
- And, update a few references, if you are using custom renderers.


I was wondering if ```Glidex``` would conflict with ```FFImageLoading``` library as they both seem to handle images more efficiently?

**Comment by jonathanpeppers** [comment]
If you use Xamarin.Android.Glide 4.11.0, it requires `TargetFrameworkVersion=v10.0` and AndroidX. You could use Xamarin.Android.Glide 4.9.0 instead if you don't want that.

I remember some comments about `FFImageLoading` here that is probably relevant: https://github.com/jonathanpeppers/glidex/issues/31#issuecomment-476854559

**Comment by sriganesh040194** [comment]
Thank you, that really helps. I will make sure to check out the linked content. 

I will close this issue :)
