### ISSUE TITLE
[Question] Should i always specify height and width request?

### ISSUE THREAD

**Issue by themronion** [jonathanpeppers/glidex#82]
Hey, so i started using your lib and i am wondering wether i should always specify the height and width request for the pic? Because when i don't sometimes the pic displays much bigger than i intend it to be, or doesn't display at all, I've seen some warnings in the console that Glidex throws that state something like this: set layout_width and layout_height to fixed dimension, When i set the requests everything works great. So i guess when specify the requests - only then i will gain the boost in performance compared to a regular XF image?

**Comment by jonathanpeppers** [comment]
@themronion yes, I would always set either `WidthRequest` or `HeightRequest` unless something else in the layout constrains the image size.

There is a general conflict on how Glide expects `ImageView`'s to be sized and how Xamarin.Forms does layout, which I've not figured out how to solve: https://github.com/jonathanpeppers/glidex/issues/10#issuecomment-433109852

**Comment by jonathanpeppers** [comment]
> only then i will gain the boost in performance compared to a regular XF image

I think you'll always get better performance using Glide; it will also scale down the image if it is larger than the `ImageView` being displayed.

**Comment by themronion** [comment]
Thanks! I will get to the process of setting the requests right away!)

**Comment by jonathanpeppers** [comment]
Let me know if you have another question, or find a bug, thanks!
