### ISSUE TITLE
What is the difference between Glidex and FFImageLoading?

### ISSUE THREAD

**Issue by AEZ314** [jonathanpeppers/glidex#86]
I don't really know if the answer is obvious because I'm a beginner. So both are image loading libraries, is there difference between the two? And can I use both of them at the same time?

**Comment by jonathanpeppers** [comment]
glidex uses a native Java library, [Glide](https://github.com/bumptech/glide), for loading all images on Android. It does not support iOS.

FFImageLoading is a completely different library that does its own thing.

Here is a blog post that might help comparing options for images:

https://www.sharpnado.com/ultimate-image-caching/

I wouldn't use both glidex and FFImageLoading at the same time. Hope that helps! Let me know if you have another question, thanks.
