### ISSUE TITLE
Glide on Xamarin Forms Shows Poor quality 

### ISSUE THREAD

**Issue by MusaSakkaf** [jonathanpeppers/glidex#89]
Hi,

I am interested on your plugin called glidex.
And it seems good to me, but what bothering me is when glide renders huge image with low quality.

This issue is exist on the orignal Google glide and it's fixed
Here to see the fix https://github.com/bumptech/glide/issues/531

I was woundering if you cloud Inform me with the solution if it's exist,,,

**Comment by MusaSakkaf** [comment]
Hi Mister Jonathan ,

I am interested on your plugin called glidex.
And it seems good to me, but what bothering me is when glide renders huge image with low quality.

this issue is exist on the orignal Google Glide and it's fixed
Here to See https://github.com/bumptech/glide/issues/531

I was woundering if you cloud Inform me with the solution if it's exist,,,

**Comment by jonathanpeppers** [comment]
https://github.com/bumptech/glide/issues/531 doesn't appear to be something they fixed, they suggested doing this:

https://github.com/bumptech/glide/issues/531#issuecomment-121633859

The only way to do this with glidex.form is to use `IGlideHandler` and customize the calls to glide, we have a basic example here:

https://github.com/jonathanpeppers/glidex/blob/master/glidex.forms.sample/RandomAlphaHandler.cs

You'll need to read [glide's documentation](https://bumptech.github.io/glide/) to figure out what to do, but I think you could check for the name of specific large images and use this `override()` method they're talking about.

If you can't find the glide APIs/methods you need, I would file issues for the Xamarin.Android.Glide binding [here](https://github.com/xamarin/XamarinComponents/issues).

**Comment by Ghasan** [comment]
Thanks,

We have solved it like this:

```csharp
    public class CustomGlideHandler : IGlideHandler
    {
        private static string[] _largeImages = { "LargeImage.png" };

        // Public

        public bool Build(ImageView imageView, ImageSource source, RequestBuilder builder, CancellationToken token)
        {
            if (source is FileImageSource imgSrc && _largeImages.Any(i => imgSrc.File.EndsWith(i)))
            {
                builder.DontTransform_T();
                builder.Into(imageView);
                return true;
            }
            else
                return false;
        }
    }
```

**Comment by MusaSakkaf** [comment]
Hi there,

We have solved it like this:

csharp
    public class CustomGlideHandler : IGlideHandler
    {
        private static string[] _largeImages = { "LargeImage.png" };

        // Public

        public bool Build(ImageView imageView, ImageSource source, RequestBuilder builder, CancellationToken token)
        {
            if (source is FileImageSource imgSrc && _largeImages.Any(i => imgSrc.File.EndsWith(i)))
            {
                builder.DontTransform_T();
                builder.Into(imageView);
                return true;
            }
            else
                return false;
        }
    }
