### ISSUE TITLE
I can't automatically resize resource images

### ISSUE THREAD

**Issue by isax5** [jonathanpeppers/glidex#92]
For some reason, I can't use my images in resources (android resources) when this package is installed
This code doesn't work with glidex:
``` xaml
<Image Source="imageName" />
```

I checked the example project and it looks like it should work

**Comment by jonathanpeppers** [comment]
So you have `Resources/drawable*/imageName.png`?

This sample has examples of this working:

https://github.com/jonathanpeppers/glidex/tree/master/glidex.forms.sample/Resources/drawable

What version of Xamarin.Forms?

**Comment by isax5** [comment]
Hi, I'm using the last versión of XF,
I checked 1000 times but everything works when I don't use Glidex, but of course, I need it for the web images!

**Comment by isax5** [comment]
Here is an example project:

https://github.com/isax5/Test_Glidex

**Comment by isax5** [comment]
If I don't set HeightRequest and WidthRequest on the Image, it doesn't adjust automatically and thus the image is not visible

**Comment by isax5** [comment]
Same as #10
