### ISSUE TITLE
Package glidex.forms 2.1.0.470 is not compatible with netstandard2.1

### ISSUE THREAD

**Issue by AndreasReitberger** [jonathanpeppers/glidex#93]
I wanted to install the nuget to my app, however I get this error:
`NU1202: Package glidex.forms 2.1.0.470 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package glidex.forms 2.1.0.470 supports: monoandroid81 (MonoAndroid,Version=v8.1)`

Is there a specific reason why it's not compatible with NS2.1?

Thank you!

**Comment by jonathanpeppers** [comment]
I think this is the same question reported here: https://github.com/jonathanpeppers/glidex/issues/66#issuecomment-655756452

`glidex.forms` only runs on Android, and so you only need to add this package to the Xamarin.Android head project. It doesn't really make sense to add to a `netstandard` library.

Hope this helps, thanks!

**Comment by AndreasReitberger** [comment]
Thanks for letting me know. I accidentally installed the package on the PLC, not the Android project ;)
